import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import { MemoizedHeader } from "../src/modules/Layout/Header/Header";
import { primary } from "@/src/SDK/theme";
import { Box } from "@mui/material";
import { MemoizedFooter } from "@/src/modules/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const navigate = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` ${inter.className}`}>
        <MemoizedHeader />

        {/* <Box sx={{ background: primary?.main }}></Box> */}
        <MemoizedFooter />
      </main>
    </>
  );
}
